- job-template:
    name: 'opx-platform-config-check-{platform}'
    node: vsi

    wrappers:
        - build-timeout:
            timeout: 120

    builders:
        - revoke-sudo
        - opx-setup:
            module: 'opx-platform-config'
        - opx-pull-docker-image
        - opx-build-module:
            module: 'all'
        - opx-test-smoke-aws:
            module: 'opx-platform-config'

    publishers:
        - post-ws-clean

- job-template:
    name: 'opx-platform-config-gate-{platform}'
    node: vsi

    wrappers:
        - build-timeout:
            timeout: 120

    builders:
        - revoke-sudo
        - opx-setup:
            module: 'opx-platform-config'
        - opx-pull-docker-image
        - opx-build-module:
            module: 'all'
        - opx-test-smoke-aws:
            module: 'opx-platform-config'

    publishers:
        - post-ws-clean

- job-group:
    name: 'opx-platform-config-jobs'
    jobs:
      - 'opx-platform-config-check-{platform}'
      - 'opx-platform-config-gate-{platform}'
