- job-template:
    name: 'opx-platform-config-check-{platform}'
    node: vsi

    wrappers:
        - build-timeout:
            timeout: 120

    builders:
        - revoke-sudo
        - opx-module-build-branch:
            module: 'opx-platform-config'
            platform: '{platform}'

    publishers:
        - post-ws-clean

- job-template:
    name: 'opx-platform-config-gate-{platform}'
    node: vsi

    wrappers:
        - build-timeout:
            timeout: 120

    builders:
        - revoke-sudo
        - opx-module-build-branch:
            module: 'opx-platform-config'
            platform: '{platform}'

    publishers:
        - post-ws-clean

- job-group:
    name: 'opx-platform-config-jobs'
    jobs:
      - 'opx-platform-config-check-{platform}'
      - 'opx-platform-config-gate-{platform}'
