includes:
  - python-file: openstack_functions.py

pipelines:
  - name: check
    description: Newly uploaded patchsets enter this pipeline to receive an initial +/-1 Verified vote from Jenkins.
    success-message: Build succeeded (check pipeline).
    failure-message: Build failed (check pipeline).
    manager: IndependentPipelineManager
    source: gerrit
    precedence: normal
    require:
      open: True
      current-patchset: True
    trigger:
      gerrit:
        - event: patchset-created
        - event: change-restored
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*(recheck|reverify)
        - event: comment-added
          require-approval:
            - verified: [-1, -2]
              username: zuul
          approval:
            - workflow: 1
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: -1

  - name: gate
    description: Changes that have been approved by core developers are enqueued in order in this pipeline, and if they pass tests in Jenkins, will be merged.
    success-message: Build succeeded (gate pipeline).
    failure-message: Build failed (gate pipeline).
    manager: DependentPipelineManager
    source: gerrit
    precedence: high
    require:
      open: True
      current-patchset: True
      approval:
        - verified: [1, 2]
          username: zuul
        - workflow: 1
    trigger:
      gerrit:
        - event: comment-added
          approval:
            - workflow: 1
        - event: comment-added
          approval:
            - code-review: 2
        - event: comment-added
          approval:
            - verified: 1
          username: zuul
    start:
      gerrit:
        verified: 0
    success:
      gerrit:
        verified: 2
        submit: true
    failure:
      gerrit:
        verified: -2
    window-floor: 20
    window-increase-factor: 2

  - name: independent-gate
    description: Changes that have been approved by core developers are enqueued in order in this pipeline, and if they pass tests in Jenkins, will be merged. Customized independent gate
    success-message: Build succeeded (independent-gate pipeline).
    failure-message: Build failed (independent-gate pipeline).
    manager: IndependentPipelineManager
    source: gerrit
    precedence: normal
    require:
      open: True
      current-patchset: True
      approval:
        - verified: [1, 2]
          username: zuul
        - workflow: 1
        - code-review: 2
    trigger:
      gerrit:
        - event: comment-added
          approval:
            - workflow: 1
        - event: comment-added
          approval:
            - code-review: 2
        - event: comment-added
          approval:
            - verified: 1
          username: zuul
    start:
      gerrit:
        verified: 0
    success:
      gerrit:
        verified: 2
        submit: true
    failure:
      gerrit:
        verified: -2
    window-floor: 20
    window-increase-factor: 2

  - name: post
    description: This pipeline runs jobs that operate after each change is merged.
    manager: IndependentPipelineManager
    source: gerrit
    precedence: low
    trigger:
      gerrit:
        - event: ref-updated
          ref: ^(?!refs/).*$

  - name: tag
    description: This pipeline runs jobs in response to any tag event.
    manager: IndependentPipelineManager
    source: gerrit
    precedence: high
    trigger:
      gerrit:
        - event: ref-updated
          ref: ^refs/tags/.*$

  - name: pre-release
    description: This pipeline runs jobs on projects in response to pre-release tags.
    manager: IndependentPipelineManager
    source: gerrit
    precedence: high
    trigger:
      gerrit:
        - event: ref-updated
          ref: ^refs/tags/[0-9]+(\.[0-9]+)*(-(a|b|rc)[0-9]+)?

  - name: release
    description: When a commit is tagged as a release, this pipeline runs jobs that publish archives and documentation.
    manager: IndependentPipelineManager
    source: gerrit
    precedence: high
    trigger:
      gerrit:
        - event: ref-updated
          ref: ^refs/tags/[0-9]+(\.[0-9]+)(\.[0-9]+)$

  - name: silent
    description: This pipeline is used for silently testing new jobs.
    manager: IndependentPipelineManager
    source: gerrit
    precedence: low
    trigger:
      gerrit:
        - event: patchset-created
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*(recheck|reverify)

  - name: experimental
    description: On-demand pipeline for requesting a run against a set of jobs that are not yet gating. Leave review comment of "check experimental" to run jobs in this pipeline.
    success-message: Build succeeded (experimental pipeline).
    failure-message: Build failed (experimental pipeline).
    manager: IndependentPipelineManager
    source: gerrit
    precedence: normal
    trigger:
      gerrit:
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*check experimental\s*$
    success:
      gerrit: {}
    failure:
      gerrit: {}

  - name: periodic-master
    description: Jobs in this queue are triggered on a timer.
    manager: IndependentPipelineManager
    source: gerrit
    precedence: low
    trigger:
      timer:
        - time: '0 */6 * * *'

  - name: periodic-release
    description: Jobs in this queue are triggered on a timer.
    manager: IndependentPipelineManager
    source: gerrit
    precedence: low
    trigger:
      timer:
        - time: '0 3 * * *'

  - name: hourly
    description: Jobs in this queue are triggered on a timer every hour.
    manager: IndependentPipelineManager
    source: gerrit
    precedence: low
    trigger:
      timer:
        - time: '0 */1 * * *'

  - name: weekly
    description: Jobs in this queue are triggered on a timer every Saturday at 6am.
    manager: IndependentPipelineManager
    source: gerrit
    precedence: low
    trigger:
      timer:
        - time: '0 6 * * 6'

  - name: periodic-stable
    description: Periodic checks of the stable branches.
    manager: IndependentPipelineManager
    source: gerrit
    precedence: low
    trigger:
      timer:
        - time: '1 6 * * *'
    failure:
      smtp:
        from: jenkins@openswitch.net
        to: openswitch-stable-maint@lists.openswitch.net
        subject: 'Stable check of {change.project} failed'

  - name: periodic-qa
    description: Periodic jobs for the QA team.
    manager: IndependentPipelineManager
    source: gerrit
    precedence: low
    trigger:
      timer:
        - time: '2 6 * * *'
    failure:
      smtp:
        from: jenkins@openswitch.net
        to: openswitch-qa@lists.openswitch.net
        subject: 'Periodic jobs for {change.project} failed'

  - name: merge-check
    description: >
      Each time a change merges, this pipeline verifies that all open changes
      on the same project are still mergeable.
    failure-message: Build failed (merge-check pipeline).
    manager: IndependentPipelineManager
    ignore-dependencies: true
    source: gerrit
    precedence: low
    require:
      approval:
        - verified: [1, 2]
          username: zuul
    trigger:
      zuul:
        - event: project-change-merged
    merge-failure:
      gerrit:
        verified: -1

project-templates:
  - name: merge-check
    merge-check:
      - noop

  - name: noop-jobs
    check:
      - noop
    gate:
      - noop

  - name: module-build
    check:
      - '{module}-check-{platform}'
    gate:
      - '{module}-gate-{platform}'
      - 'md-gate'

  - name: opx-module-build
    check:
      - '{module}-check-{platform}'
    gate:
      - '{module}-gate-{platform}'

# Jobs definitions are not required, but help us filter unrequired check jobs
# We still run the jobs during gate
jobs:
  - name: ^opx-.*(check|gate).*$
    skip-if:
      - project: ^opx/.*$
        all-files-match-any:
          - ^.*\.md$

projects:
  - name: infra/website
    template:
      - name: merge-check
    check:
      - website-check
    gate:
      - website-gate
    hourly:
      - website-stage-hourly

  - name: opx/opx-alarm
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-alarm
       platform: genericx86-64

  - name: opx/opx-base-model
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-base-model
       platform: genericx86-64

  - name: opx/opx-build
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-build
       platform: genericx86-64

  - name: opx/opx-common-utils
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-common-utils
       platform: genericx86-64

  - name: opx/opx-core
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-core
       platform: genericx86-64

  - name: opx/opx-cps
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-cps
       platform: genericx86-64

  - name: opx/opx-db-sql
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-db-sql
       platform: genericx86-64

  - name: opx/opx-docs
    template:
     - name: merge-check
     - name: noop-jobs

  - name: opx/opx-logging
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-logging
       platform: genericx86-64

  - name: opx/opx-manifest
    template:
     - name: merge-check
     - name: noop-jobs

  - name: opx/opx-mlnx-sdi-sys
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-mlnx-sdi-sys
       platform: genericx86-64

  - name: opx/opx-nas-acl
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-nas-acl
       platform: genericx86-64

  - name: opx/opx-nas-apps
    template:
     - name: merge-check
     - name: noop-jobs

  - name: opx/opx-nas-common
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-nas-common
       platform: genericx86-64

  - name: opx/opx-nas-daemon
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-nas-daemon
       platform: genericx86-64

  - name: opx/opx-nas-interface
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-nas-interface
       platform: genericx86-64

  - name: opx/opx-nas-l2
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-nas-l2
       platform: genericx86-64

  - name: opx/opx-nas-l3
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-nas-l3
       platform: genericx86-64

  - name: opx/opx-nas-linux
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-nas-linux
       platform: genericx86-64

  - name: opx/opx-nas-ndi
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-nas-ndi
       platform: genericx86-64

  - name: opx/opx-nas-ndi-api
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-nas-ndi-api
       platform: genericx86-64

  - name: opx/opx-nas-qos
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-nas-qos
       platform: genericx86-64

  - name: opx/opx-onie-installer
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-onie-installer
       platform: genericx86-64

  - name: opx/opx-pas
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-pas
       platform: genericx86-64

  - name: opx/opx-platform-config
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-platform-config
       platform: genericx86-64

  - name: opx/opx-sai-common
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-sai-common
       platform: genericx86-64

  - name: opx/opx-sai-common-utils
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-sai-common-utils
       platform: genericx86-64

  - name: opx/opx-sai-vm
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-sai-vm
       platform: genericx86-64

  - name: opx/opx-sdi-api
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-sdi-api
       platform: genericx86-64

  - name: opx/opx-sdi-device-drivers
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-sdi-device-drivers
       platform: genericx86-64

  - name: opx/opx-sdi-framework
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-sdi-framework
       platform: genericx86-64

  - name: opx/opx-sdi-sys
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-sdi-sys
       platform: genericx86-64

  - name: opx/opx-sdi-sys-vm
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-sdi-sys-vm
       platform: genericx86-64

  - name: opx/opx-snmp
    template:
     - name: merge-check
     - name: noop-jobs

  - name: opx/opx-test
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-test
       platform: genericx86-64

  - name: opx/opx-tmpctl
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-tmpctl
       platform: genericx86-64

  - name: opx/opx-tools
    template:
     - name: merge-check
     - name: opx-module-build
       module: opx-tools
       platform: genericx86-64

  - name: opx/ansible-role-opx-acl
    template:
     - name: merge-check
     - name: noop-jobs

  - name: opx/ansible-role-opx-mac
    template:
     - name: merge-check
     - name: noop-jobs

  - name: opx/ansible-role-opx-qos
    template:
     - name: merge-check
     - name: noop-jobs

  - name: opx/ansible-role-opx-system
    template:
     - name: merge-check
     - name: noop-jobs

  - name: opx/ansible-opx-examples
    template:
     - name: merge-check
     - name: noop-jobs
